import Foundation

/// Presentation and saved-library facts, independent of the server's wire schema.
struct MovieMetadata: Codable, Hashable, Sendable, Identifiable {
    let mediaID: String
    var title: String
    var summary: String?
    var genre: String?
    var durationSeconds: Double?
    var resolution: String?
    var hdr: String?
    var sourceSizeBytes: UInt64?
    var audioTracks: [MovieAudioTrack] = []
    var captions: [MovieCaption] = []
    var chapters: [MovieChapter] = []
    var remoteArtworkPath: String?
    var id: String { mediaID }
    var displayTitle: String { DisplayTitle.clean(title) }

    init(mediaID: String, title: String, durationSeconds: Double? = nil, resolution: String? = nil) {
        self.mediaID = mediaID
        self.title = title
        self.durationSeconds = durationSeconds
        self.resolution = resolution
    }

    init(item: MediaItem) {
        self.init(mediaID: item.id, title: item.title,
                  durationSeconds: item.durationSeconds.map(Double.init), resolution: item.resolution)
        summary = item.plot ?? item.about
        genre = item.genre
        hdr = item.hdr
        sourceSizeBytes = item.sizeBytes > 0 ? item.sizeBytes : nil
        audioTracks = item.audioTracks.map(MovieAudioTrack.init)
        captions = item.captions.map(MovieCaption.init)
        chapters = item.chapters.map(MovieChapter.init)
        remoteArtworkPath = item.artURL
    }

    init(entry: LibraryEntry) {
        self.init(mediaID: entry.id, title: entry.title,
                  durationSeconds: entry.durationSeconds.map(Double.init), resolution: entry.resolution)
        summary = entry.about
        genre = entry.genre
        hdr = entry.hdr
        sourceSizeBytes = entry.sizeBytes
        remoteArtworkPath = entry.artURL
    }
}

struct MovieAudioTrack: Codable, Hashable, Sendable, Identifiable {
    let serverIndex: Int?
    let codec: String
    let channels: Int
    let language: String?
    let title: String?
    let isDefault: Bool
    var id: String { serverIndex.map(String.init) ?? "\(language ?? "")|\(title ?? "")|\(codec)|\(channels)" }
    var displayName: String { title ?? language?.uppercased() ?? "Audio" }
    var channelDescription: String {
        switch channels {
        case 1: "Mono"
        case 2: "Stereo"
        case 3...: "\(channels) channels"
        default: "Channels unknown"
        }
    }
    var selectionLabel: String { "\(displayName) · \(codec.uppercased()) · \(channelDescription)\(isDefault ? " · Default" : "")" }

    init(_ track: AudioTrack) {
        serverIndex = track.index
        codec = track.codec
        channels = track.channels
        language = track.language
        title = track.title
        isDefault = track.default
    }
}

struct MovieCaption: Codable, Hashable, Sendable, Identifiable {
    let serverIndex: Int?
    let label: String
    let language: String?
    let isDefault: Bool
    let isForced: Bool?
    let remotePath: String?
    let supportedSidecar: Bool
    var id: String { serverIndex.map(String.init) ?? "\(language ?? "")|\(label)" }

    init(_ caption: CaptionTrack) {
        serverIndex = caption.index
        label = caption.label
        language = caption.language
        isDefault = caption.default
        isForced = nil
        remotePath = caption.url
        supportedSidecar = caption.isPlayableOnDevice
    }
}

struct MovieChapter: Codable, Hashable, Sendable, Identifiable {
    let id: Int
    let title: String
    let startSeconds: Double
    let endSeconds: Double

    init(id: Int, title: String, startSeconds: Double, endSeconds: Double) {
        self.id = id
        self.title = title
        self.startSeconds = startSeconds
        self.endSeconds = endSeconds
    }

    init(_ chapter: Chapter) {
        id = chapter.index
        title = chapter.title
        startSeconds = chapter.startSeconds
        endSeconds = chapter.endSeconds
    }
}

struct OfflineCaption: Codable, Hashable, Sendable, Identifiable {
    let id: UUID
    let label: String
    let language: String?
    let isDefault: Bool
    let isForced: Bool?
    let fileName: String
}

enum OfflineResourceKind: String, Codable, Hashable, Sendable {
    case media, artwork, caption
}

/// Names are generated by the app; advertised remote URLs are never local paths.
struct OfflineResource: Codable, Hashable, Sendable, Identifiable {
    let id: UUID
    let kind: OfflineResourceKind
    let remotePath: String
    let fileName: String
    let required: Bool
    var caption: OfflineCaption? = nil
    var runtimeID: String {
        switch kind {
        case .media: "video"
        case .artwork: "artwork"
        case .caption: id.uuidString.lowercased()
        }
    }
}

struct OfflinePackagePlan: Codable, Hashable, Sendable {
    let movie: MovieMetadata
    let resources: [OfflineResource]

    init(metadata: DownloadTaskMetadata, movie: MovieMetadata) {
        self.movie = movie
        var resources = [OfflineResource(id: metadata.recordID, kind: .media,
                                         remotePath: metadata.serverPath ?? "",
                                         fileName: "media.\(OfflinePackagePath.safeExtension(metadata.fileExtension))", required: true)]
        for caption in movie.captions where caption.supportedSidecar {
            guard let remotePath = caption.remotePath else { continue }
            let id = UUID()
            let fileName = "caption-\(id.uuidString.lowercased()).vtt"
            let local = OfflineCaption(id: id, label: caption.label, language: caption.language,
                                       isDefault: caption.isDefault, isForced: caption.isForced, fileName: fileName)
            resources.append(OfflineResource(id: id, kind: .caption, remotePath: remotePath,
                                              fileName: fileName, required: true, caption: local))
        }
        if let path = movie.remoteArtworkPath {
            resources.append(OfflineResource(id: UUID(), kind: .artwork, remotePath: path,
                                              fileName: "artwork.image", required: false))
        }
        self.resources = resources
    }
}

enum OfflinePackagePath {
    static func safeExtension(_ value: String) -> String {
        let ext = String(value.lowercased().filter { $0.isASCII && ($0.isLetter || $0.isNumber) }.prefix(16))
        return ext.isEmpty ? "media" : ext
    }

    static func isSafeLeaf(_ value: String) -> Bool {
        !value.isEmpty && value != "." && value != ".." && !value.contains("/") && !value.contains("\\")
            && value != "manifest.json" && value != "queue.json" && value != "state.json"
    }
}
